ALTER TABLE pool6.users ADD COLUMN IF NOT EXISTS last_seen_at TIMESTAMPTZ;
ALTER TABLE pool6.users ADD COLUMN IF NOT EXISTS show_online BOOLEAN DEFAULT true;
ALTER TABLE pool6.users ADD COLUMN IF NOT EXISTS show_last_seen BOOLEAN DEFAULT true;
